routes/admin.php
<?php


use App\Http\Controllers\Admin\RoleController;
use Illuminate\Support\Facades\Route;


Route::get('/dashboard', 'LoaderController@dashboard')->name('dashboard');

route::get('panel', 'PanelController@index')->name('panel');
route::get('panel/edit', 'PanelController@edit')->name('panel.edit');
route::patch('panel/update', 'PanelController@update')->name('panel.update');

// students
route::resource('students', 'InfoStudentController');
route::get('student/profile/unchecked', 'InfoStudentController@uncheckedProfiles')->name('student.profile.unchecked');
route::get('student/profile/submit/{student}', 'InfoStudentController@submitProfiles')->name('student.profile.submit');

// students
//route::resource('classStudents', 'ClassStudentController');

// teachers
route::resource('teachers', 'InfoTeacherController');

// cadres
route::resource('cadres', 'CadreController');

// teacherCourses
route::resource('teacherCourses', 'TeacherCourseController');

// azmoons
route::resource('azmoons', 'AzmoonController');
route::get('azmoon/edit/date/{azmoon}', 'AzmoonController@editDate')->name('azmoon.date.edit');
route::patch('azmoon/update/date/{azmoon}', 'AzmoonController@updateDate')->name('azmoon.date.update');


route::resource('azmoonSoalatFiles', 'AzmoonSoalatFileController');
route::resource('porseshnamehs', 'AzmoonPorseshnamehController');
route::resource('soalbsoals', 'AzmoonSoalbsoalController');
route::get('azmoon/result/reset{azmoon}', 'AzmoonController@resultReset')->name('azmoons.result.reset');
route::get('azmoon/change/status/{azmoon}', 'AzmoonController@changeStatus')->name('azmoon.change.status');

route::post('insert.advance.soal', 'AzmoonPorseshnamehController@insertAdvanceSoal')->name('insert.advance.soal');
route::post('store.advanced.soal', 'AzmoonPorseshnamehController@StoreAdvancedSoal')->name('advanced.porseshnamehs.store');

route::get('azmoon/advanced/proseshnamefile/create/{azmoon}', 'AzmoonAdvancedFileController@create')->name('advanced.porseshname.file.create');
route::post('azmoon/advanced/proseshnamefile/store/{azmoon}', 'AzmoonAdvancedFileController@store')->name('advanced.porseshname.file.store');
route::delete('azmoon/advanced/proseshnamefile/destroy/{advancedFile}', 'AzmoonAdvancedFileController@destroy')->name('advanced.porseshname.file.destroy');

route::get('azmoon/analytical/report/ago/{azmoon}', 'Azmoon\AnalyticalReportController@agoReport')->name('azmoon.analytical.report.ago');

route::get('azmoon/report/{azmoon}', 'AzmoonController@exportReport')->name('azmoon.reports');
route::get('azmoon/report/quick/{azmoon}/{value}', 'AzmoonController@quickReport')->name('azmoon.quick.reports');
route::get('azmoon/result/reset/user/{result}', 'AzmoonController@resultResetUser')->name('azmoon.result.reset.user');

Route::resource('productCategories', 'Product\ProductCategoryController');
Route::resource('products', 'Product\ProductController');

Route::resource('ticketCategories', 'TicketCategoryController');
Route::resource('tickets', 'TicketController');

route::resource('custom/fields', 'CustomFieldController');
/*route::get('custom/fields','CustomFieldController@index')->name('custom.fields.index');
route::get('custom/field/create','CustomFieldController@create')->name('custom.fields.create');
route::post('custom/field/store','CustomFieldController@store')->name('custom.fields.store');*/


Route::resource('roles', 'RoleController');
//Route::resource('users', UserController::class);
//Route::resource('products', ProductController::class);

route::resource('defaultCovers', 'DefaultCoverController');
route::resource('exclusives', 'Azmoon\AzmoonExclusiveController');

route::get('setting','SettingController@settingView')->name('setting.all');
route::get('setting/sms','SettingController@smsStatus')->name('setting.sms');


Route::get('/{vue_capture?}', function () {
    return view('panel.admin.master');
})->where('vue_capture', '[\/\w\.-].*');

routes/dashboard.php
<?php

routes/web.php
<?php

use App\CustomizeField;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

route::get('test',function (){
   return $base = \App\EducationalBase::query()->where('base_title','پنجم')->first();
});

route::get('canceled','ErrorPageController@canceled')->name('error.page.canceled');

Route::get('/azmoon/start/{azmoon_code}','Site\HomeController@guestStartAzmoon');

Route::get('/','Site\HomeController@index')->name('site.index');

Route::get('stores','Site\ProductController@index')->name('site.products.index');
Route::get('/product/{product}','Site\ProductController@show')->name('site.products.show');

Route::get('shop-cart','Site\ShopCartController@index')->name('site.shop.carts.index');

Route::get('/welcome', function () {
    /*$users = \App\User::all();
    $characters = '0123456789abcdefghijklmnopqrstuvwxyz';
    $charactersLength = strlen($characters);
    $rr = 0;
    foreach ($users as $user){
        do{
            //$rr++;
            $randomString = '';
            for ($i = 0; $i <= 8; $i++) {
                $randomString .= $characters[rand(0, $charactersLength - 1)];
            }
            $check =\App\User::where('private_code',$randomString)->get();
            //print_r($randomString);
            //echo '</br>';

        }while(!$check->isEmpty());
        $user->update(['private_code'=>$randomString]);

    }*/
    \App\User::create([
        'level'=>'admin',
        'email'=>'admin@admin.com',
        'first_name'=>'saeed',
        'last_name'=>'gsm',
        'password'=>bcrypt('11111111'),
    ]);

   // $oldClasses = \Illuminate\Support\Facades\DB::table('classes')->orderBy('id','asc')->get();
    /*foreach ($oldClasses as $class){

        $newClass = \App\EducationalClass::create([
            'base_id'=>$class->level,
            'class_title'=>$class->name
        ]);
        $classStudents = \Illuminate\Support\Facades\DB::table('old_users')
            ->orderBy('id','asc')
            ->whereNotNull('usercode')
            ->where('usercode','!=',0)
            ->where('class',$class->id)
            ->get();

        if ($classStudents->isNotEmpty()){
            foreach ($classStudents as $st){
                $users = \App\User::all();
                $characters = '0123456789abcdefghijklmnopqrstuvwxyz';
                $charactersLength = strlen($characters);
                $rr = 0;
               // foreach ($users as $us){
                    do{
                        //$rr++;
                        $randomString = '';
                        for ($i = 0; $i <= 8; $i++) {
                            $randomString .= $characters[rand(0, $charactersLength - 1)];
                        }
                        $check =\App\User::where('private_code',$randomString)->get();


                    }while(!$check->isEmpty());
                    //$user->update(['private_code'=>$randomString]);

              //  }

                $user = \App\User::create([
                    'private_code'=>$randomString,
                    'level'=>'student',
                    'usercode'=>$st->usercode,
                    'userpass'=>$st->pass,
                    'password'=>bcrypt($st->pass),
                    'first_name'=>$st->getname,
                    'last_name'=>$st->getfamily,
                ]);
                \App\InfoStudent::create(['user_id'=>$user->id]);
                \App\RegisterClassStudent::create([
                    'user_id'=>$user->id,
                    'base_id'=>$newClass->base_id,
                    'class_id'=>$newClass->id
                ]);
            }
        }
    }*/
    /*$stOld2 = \Illuminate\Support\Facades\DB::table('old_users')
        ->orderBy('id','asc')
        ->whereNotNull('usercode')
        ->where('usercode','!=',0)
        // ->whereNull('class','and')
        ->where('class','==',0)
        //  ->orWhere('class','==',$v)
        ->get();
    foreach ($stOld2 as $item){

        $characters = '0123456789abcdefghijklmnopqrstuvwxyz';
        $charactersLength = strlen($characters);
        do{
            $randomString = '';
            for ($i = 0; $i <= 8; $i++) {
                $randomString .= $characters[rand(0, $charactersLength - 1)];
            }
            $check =\App\User::where('private_code',$randomString)->get();


        }while(!$check->isEmpty());

        $user = \App\User::create([
            'private_code'=>$randomString,
            'level'=>'student',
            'usercode'=>$item->usercode,
            'userpass'=>$item->pass,
            'password'=>bcrypt($item->pass),
            'first_name'=>$item->getname,
            'last_name'=>$item->getfamily,
        ]);
        \App\InfoStudent::create(['user_id'=>$user->id]);
        \App\RegisterClassStudent::create([
            'user_id'=>$user->id,
            'base_id'=>$item->level,
            //'class_id'=>
        ]);
    }*/
    //$oCount = $oldClasses->count();
   // $users = \App\User::all();
//$row=4;
    //return view('welcome');
})->name('home.index');

route::get('check/acc/pp','CheckAccountController@copy')->name('check.account.copy');
route::get('check/acc','CheckAccountController@check')->name('check.account');
route::post('check/acc/st','CheckAccountController@checkAccount')->name('check.account.st');

// http error code pages
//route::get('404','Site/HttpCodePageController@404')->name('http.code.404');

Route::group(['namespace' => 'Auth'] , function (){
    // Authentication Routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::get('logout', 'LoginController@logout')->name('logout');

    // Registration Routes...
    Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'RegisterController@register');

    Route::get('confirm/code','RegisterController@confirmRegisterCodeForm')->name('register.confirm.code.form');
    Route::post('confirm/code','RegisterController@getCode')->name('register.confirm.code');

    Route::get('/insert/phone/{pc}','LoginController@insertPhoneForm')->name('user.insert.phone.form');
    Route::post('/check/phone/{pc}','LoginController@checkPhone')->name('user.check.phone');

   // Route::get('/check/phone/{pc}','LoginController@checkPhoneForm')->name('user.check.phone.exist');

    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset')->name('password.update');

    Route::get('password/confirm', 'ConfirmPasswordController@showConfirmForm')->name('password.confirm');
    Route::post('password/confirm', 'ConfirmPasswordController@confirm');

    Route::get('email/verify', 'VerificationController@show')->name('verification.notice');
    Route::get('email/verify/{id}/{hash}', 'VerificationController@verify')->name('verification.verify');
    Route::post('email/resend', 'VerificationController@resend')->name('verification.resend');



});



Route::get('/home', 'HomeController@index')->name('home');

resources/views/panel/admin/section/footer.blade.php
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                2020 © saeedgsm.
            </div>
            <div class="col-sm-6">
                <div class="text-sm-right d-none d-sm-block">
                    توسعه داده شده توسط  - سعید قاسمی 09021410090
                </div>
            </div>
        </div>
    </div>
</footer>

resources/views/panel/admin/section/header.blade.php
<header id="page-topbar">
    <div class="navbar-header">
        <div class="d-flex">
            <!-- LOGO -->
            <div class="navbar-brand-box" style="background: #4865d8;">
                <a href="/" class="logo logo-dark">
                                <span class="logo-sm">
                                    <img src="{{ asset('imgs/logo-panel.png') }}" alt="" height="22">
                                </span>
                    <span class="logo-lg">
                                    <img src="{{ asset('imgs/logo-panel.png') }}" alt="" height="40">
                                </span>
                </a>
            </div>

            <button type="button" class="btn btn-sm px-3 font-size-24 header-item waves-effect" id="vertical-menu-btn">
                <i class="mdi mdi-backburger"></i>
            </button>
        </div>



        <div class="d-flex">
            @can('role-edit')
            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item waves-effect" id="page-header-flag-dropdown"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="" src="{{ asset('imgs/logo-panel.png') }}" alt="Header Language" height="54" style="
    border-radius: 10px;">
                </button>
                <div class="dropdown-menu dropdown-menu-right">
                    <!-- item-->
                    <a href="{{ route('admin.cadres.index',['level'=>'agency']) }}" class="dropdown-item notify-item">
                        <img src="{{ asset('assets/images/map.png') }}" alt="user-image" class="mr-2" height="42"><span class="align-middle">نمایندگان</span>
                    </a>
                    <!-- item-->
                    <a href="{{ route('admin.cadres.index',['level'=>'teacher']) }}" class="dropdown-item notify-item">
                        <img src="{{ asset('assets/images/professors.png') }}" alt="user-image" class="mr-2" height="42"><span class="align-middle">اساتید</span>
                    </a>

                    <!-- item-->
                    <a href="{{ route('admin.cadres.index',['level'=>'admin']) }}" class="dropdown-item notify-item">
                        <img src="{{ asset('assets/images/staff.png') }}" alt="user-image" class="mr-2" height=42"><span class="align-middle">کارکنان مجموعه</span>
                    </a>


                </div>
            </div>
            <div class="dropdown d-inline-block d-lg-none ml-2">
                <button type="button" class="btn header-item noti-icon waves-effect" id="page-header-search-dropdown"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="mdi mdi-magnify"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right p-0"
                     aria-labelledby="page-header-search-dropdown">

                    <form class="p-3">
                        <div class="form-group m-0">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Search ..." aria-label="Recipient's username">
                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="submit"><i class="mdi mdi-magnify"></i></button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            @endcan


            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item waves-effect" id="page-header-user-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="rounded-circle header-profile-user" src="{{ asset(auth()->user()->userAvatar()) }}" alt="Header Avatar">
                    <span class="d-none d-sm-inline-block ml-1">{{ auth()->user()->first_name ?? '' }} {{ auth()->user()->last_name ?? '' }}</span>
                    <i class="mdi mdi-chevron-down d-none d-sm-inline-block"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-right">
                    <!-- item-->
                    <a class="dropdown-item" href="{{ route('admin.panel') }}"><i class="mdi mdi-face-profile font-size-16 align-middle mr-1"></i> ناحیه کاربری</a>

                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{{ route('logout') }}"><i class="mdi mdi-logout font-size-16 align-middle mr-1"></i> خروج</a>
                </div>
            </div>

        </div>
    </div>
</header>

resources/views/panel/admin/section/verticalMenu.blade.php
<div class="vertical-menu">

    <div data-simplebar class="h-100">

        <!--- Sidemenu -->
        <div id="sidebar-menu">
            <!-- Left Menu Start -->
            <ul class="metismenu list-unstyled" id="side-menu">
                <li class="menu-title">منو</li>


                <li>
                    <a href="{{ route('admin.dashboard') }}" class="waves-effect">
                        <div class="d-inline-block mr-1"><i class="uim uim-airplay"></i></div>
                        <span>داشبرد</span>
                    </a>
                </li>
                <li>
                    <a href="javascript: void(0);" class="has-arrow waves-effect">
                        <div class="d-inline-block mr-1"><i class="uim uim-calender"></i></div>
                        <span> دوره ها</span>
                    </a>
                    <ul class="sub-menu" aria-expanded="false">
                        <li>
                            <router-link :to="{name : 'Courses'}"> دوره ها</router-link>
                        </li>

                    </ul>
                </li>
                <li>
                    <a href="javascript: void(0);" class="has-arrow waves-effect">
                        <div class="d-inline-block mr-1"><i class="uim uim-vector-square-alt"></i></div>
                        <span>  مدیریت آموزش</span>
                    </a>
                    <ul class="sub-menu" aria-expanded="false" style="background: aliceblue;">
                        <li><router-link :to="{name : 'AllBases'}">پایه های آموزشی</router-link></li>
                        <li><router-link :to="{name : 'Books'}">کتاب ها</router-link></li>
                        <li style="background: beige;"><a href="javascript: void(0);" class="has-arrow" aria-expanded="true">پایه ها</a>
                            <ul class="sub-menu mm-collapse" aria-expanded="true" style="">
                                @foreach(\App\EducationalBase::latest()->take(3)->get() as $item)
                                    <li><a href="javascript: void(0);">{{ $item->base_title }}</a></li>
                                @endforeach
                            </ul>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="javascript: void(0);" class="has-arrow waves-effect">
                        <div class="d-inline-block mr-1"><i class="uim uim-document-layout-center"></i></div>
                        <span> کاربران</span>
                    </a>
                    <ul class="sub-menu" aria-expanded="false" style="background: aliceblue;">
                        <li><router-link :to="{name : 'Students'}">دانش آموزان</router-link></li>
                        <li><a href="{{ route('admin.student.profile.unchecked') }}">بررسی پروفایل دانش آموزان</a></li>
                    </ul>
                </li>
                <li >
                    <a href="javascript: void(0);" class="has-arrow waves-effect">
                        <div class="d-inline-block mr-1"><i class="uim uim-circle-layer"></i></div>
                        <span> ساختار</span>
                    </a>
                    <ul class="sub-menu" aria-expanded="false" style="background: aliceblue;">
                        <li>
                            <router-link :to="{name : 'ActiveCourseStudents'}">دانش آموزان دوره فعال</router-link>
                        </li>


                        <li style="background: beige;">
                            <a href="javascript: void(0);" class="has-arrow " aria-expanded="false" >
                                <div class="d-inline-block mr-1"><i class="uim uim-box"></i></div>
                                <strong>سفارش سازی</strong>
                            </a>
                            <ul class="sub-menu mm-collapse" aria-expanded="false" style="">
                                <li>
                                    <router-link :to="{name : 'Fields'}">سفارش سازی فیلد ها</router-link>
                                </li>
                                <li><a href="{{ route('admin.fields.index') }}"> فیلد های ثابت</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="javascript: void(0);" class="has-arrow waves-effect">
                        <div class="d-inline-block mr-1"><i class="uim uim-check-circle"></i></div>
                        <span>آزمون</span>
                    </a>
                    <ul class="sub-menu" aria-expanded="false">
                        <li><router-link :to="{name : 'Azmoons'}">آزمون ها</router-link></li>


                    </ul>
                </li>
                <li>
                    <a href="javascript: void(0);" class="has-arrow waves-effect">
                        <div class="d-inline-block mr-1"><i class="mdi mdi-tag-outline"></i></div>
                        <span>فروشگاه</span>
                    </a>
                    <ul class="sub-menu" aria-expanded="false">
                        <li><a href="{{ route('admin.productCategories.index') }}">دسته بندی</a></li>
                        <li><a href="{{ route('admin.products.index') }}">محصولات</a></li>
                    </ul>
                </li>
                <li>
                    <a href="javascript: void(0);" class="has-arrow waves-effect">
                        <div class="d-inline-block icons-sm mr-1"><i class="mdi mdi-ticket"></i></div>
                        <span>پشتیبانی تیکت</span>
                    </a>
                    <ul class="sub-menu" aria-expanded="false">
                        <li><a href="{{ route('admin.ticketCategories.index') }}">دسته بندی</a></li>
                        <li><a href="{{ route('admin.tickets.index') }}">تیکت ها</a></li>
                    </ul>
                </li>
                @can('role-edit')
                    <li>
                        <a href="javascript: void(0);" class="has-arrow waves-effect">
                            <div class="d-inline-block icons-sm mr-1"><i
                                        class="mdi mdi-card-bulleted-settings-outline"></i></div>
                            <span>تنظیمات سایت</span>
                        </a>
                        <ul class="sub-menu" aria-expanded="false">
                            <li><router-link :to="{name : 'TariffBases'}">تعرفه ثبت نام پایه ها</router-link></li>
                            <li><router-link :to="{name : 'SMSGroupClasses'}">پیامک گروهی</router-link></li>
                            <li><a href="{{ route('admin.setting.all') }}">تنظیمات</a></li>
                            <li><a href="{{ route('admin.roles.index') }}">سطح دسترسی</a></li>
                            <li><a href="{{ route('admin.defaultCovers.index') }}">کاور پیش فرض</a></li>
                        </ul>
                    </li>
                @endcan

            </ul>

        </div>
        <!-- Sidebar -->
    </div>
</div>