routes/admin.php
<?php


use App\Http\Controllers\Admin\RoleController;
use Illuminate\Support\Facades\Route;


Route::get('/dashboard', 'LoaderController@dashboard')->name('dashboard');

route::get('panel', 'PanelController@index')->name('panel');
route::get('panel/edit', 'PanelController@edit')->name('panel.edit');
route::patch('panel/update', 'PanelController@update')->name('panel.update');

// students
route::resource('students', 'InfoStudentController');
route::get('student/profile/unchecked', 'InfoStudentController@uncheckedProfiles')->name('student.profile.unchecked');
route::get('student/profile/submit/{student}', 'InfoStudentController@submitProfiles')->name('student.profile.submit');

// students
//route::resource('classStudents', 'ClassStudentController');

// teachers
route::resource('teachers', 'InfoTeacherController');

// cadres
route::resource('cadres', 'CadreController');

// teacherCourses
route::resource('teacherCourses', 'TeacherCourseController');

// azmoons
route::resource('azmoons', 'AzmoonController');
route::get('azmoon/edit/date/{azmoon}', 'AzmoonController@editDate')->name('azmoon.date.edit');
route::patch('azmoon/update/date/{azmoon}', 'AzmoonController@updateDate')->name('azmoon.date.update');


route::resource('azmoonSoalatFiles', 'AzmoonSoalatFileController');
route::resource('porseshnamehs', 'AzmoonPorseshnamehController');
route::resource('soalbsoals', 'AzmoonSoalbsoalController');
route::get('azmoon/result/reset{azmoon}', 'AzmoonController@resultReset')->name('azmoons.result.reset');
route::get('azmoon/change/status/{azmoon}', 'AzmoonController@changeStatus')->name('azmoon.change.status');

route::post('insert.advance.soal', 'AzmoonPorseshnamehController@insertAdvanceSoal')->name('insert.advance.soal');
route::post('store.advanced.soal', 'AzmoonPorseshnamehController@StoreAdvancedSoal')->name('advanced.porseshnamehs.store');

route::get('azmoon/advanced/proseshnamefile/create/{azmoon}', 'AzmoonAdvancedFileController@create')->name('advanced.porseshname.file.create');
route::post('azmoon/advanced/proseshnamefile/store/{azmoon}', 'AzmoonAdvancedFileController@store')->name('advanced.porseshname.file.store');
route::delete('azmoon/advanced/proseshnamefile/destroy/{advancedFile}', 'AzmoonAdvancedFileController@destroy')->name('advanced.porseshname.file.destroy');

route::get('azmoon/analytical/report/ago/{azmoon}', 'Azmoon\AnalyticalReportController@agoReport')->name('azmoon.analytical.report.ago');

route::get('azmoon/report/{azmoon}', 'AzmoonController@exportReport')->name('azmoon.reports');
route::get('azmoon/report/quick/{azmoon}/{value}', 'AzmoonController@quickReport')->name('azmoon.quick.reports');
route::get('azmoon/result/reset/user/{result}', 'AzmoonController@resultResetUser')->name('azmoon.result.reset.user');

Route::resource('productCategories', 'Product\ProductCategoryController');
Route::resource('products', 'Product\ProductController');

Route::resource('ticketCategories', 'TicketCategoryController');
Route::resource('tickets', 'TicketController');

route::resource('custom/fields', 'CustomFieldController');
/*route::get('custom/fields','CustomFieldController@index')->name('custom.fields.index');
route::get('custom/field/create','CustomFieldController@create')->name('custom.fields.create');
route::post('custom/field/store','CustomFieldController@store')->name('custom.fields.store');*/


Route::resource('roles', 'RoleController');
//Route::resource('users', UserController::class);
//Route::resource('products', ProductController::class);

route::resource('defaultCovers', 'DefaultCoverController');
route::resource('exclusives', 'Azmoon\AzmoonExclusiveController');

route::get('setting','SettingController@settingView')->name('setting.all');
route::get('setting/sms','SettingController@smsStatus')->name('setting.sms');


Route::get('/{vue_capture?}', function () {
    return view('panel.admin.master');
})->where('vue_capture', '[\/\w\.-].*');

routes/dashboard.php
<?php

routes/web.php
<?php

use App\CustomizeField;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

route::get('test',function (){
   return $base = \App\EducationalBase::query()->where('base_title','پنجم')->first();
});

route::get('canceled','ErrorPageController@canceled')->name('error.page.canceled');

Route::get('/azmoon/start/{azmoon_code}','Site\HomeController@guestStartAzmoon');

Route::get('/','Site\HomeController@index')->name('site.index');

Route::get('stores','Site\ProductController@index')->name('site.products.index');
Route::get('/product/{product}','Site\ProductController@show')->name('site.products.show');

Route::get('shop-cart','Site\ShopCartController@index')->name('site.shop.carts.index');

Route::get('/welcome', function () {
    /*$users = \App\User::all();
    $characters = '0123456789abcdefghijklmnopqrstuvwxyz';
    $charactersLength = strlen($characters);
    $rr = 0;
    foreach ($users as $user){
        do{
            //$rr++;
            $randomString = '';
            for ($i = 0; $i <= 8; $i++) {
                $randomString .= $characters[rand(0, $charactersLength - 1)];
            }
            $check =\App\User::where('private_code',$randomString)->get();
            //print_r($randomString);
            //echo '</br>';

        }while(!$check->isEmpty());
        $user->update(['private_code'=>$randomString]);

    }*/
    \App\User::create([
        'level'=>'admin',
        'email'=>'admin@admin.com',
        'first_name'=>'saeed',
        'last_name'=>'gsm',
        'password'=>bcrypt('11111111'),
    ]);

   // $oldClasses = \Illuminate\Support\Facades\DB::table('classes')->orderBy('id','asc')->get();
    /*foreach ($oldClasses as $class){

        $newClass = \App\EducationalClass::create([
            'base_id'=>$class->level,
            'class_title'=>$class->name
        ]);
        $classStudents = \Illuminate\Support\Facades\DB::table('old_users')
            ->orderBy('id','asc')
            ->whereNotNull('usercode')
            ->where('usercode','!=',0)
            ->where('class',$class->id)
            ->get();

        if ($classStudents->isNotEmpty()){
            foreach ($classStudents as $st){
                $users = \App\User::all();
                $characters = '0123456789abcdefghijklmnopqrstuvwxyz';
                $charactersLength = strlen($characters);
                $rr = 0;
               // foreach ($users as $us){
                    do{
                        //$rr++;
                        $randomString = '';
                        for ($i = 0; $i <= 8; $i++) {
                            $randomString .= $characters[rand(0, $charactersLength - 1)];
                        }
                        $check =\App\User::where('private_code',$randomString)->get();


                    }while(!$check->isEmpty());
                    //$user->update(['private_code'=>$randomString]);

              //  }

                $user = \App\User::create([
                    'private_code'=>$randomString,
                    'level'=>'student',
                    'usercode'=>$st->usercode,
                    'userpass'=>$st->pass,
                    'password'=>bcrypt($st->pass),
                    'first_name'=>$st->getname,
                    'last_name'=>$st->getfamily,
                ]);
                \App\InfoStudent::create(['user_id'=>$user->id]);
                \App\RegisterClassStudent::create([
                    'user_id'=>$user->id,
                    'base_id'=>$newClass->base_id,
                    'class_id'=>$newClass->id
                ]);
            }
        }
    }*/
    /*$stOld2 = \Illuminate\Support\Facades\DB::table('old_users')
        ->orderBy('id','asc')
        ->whereNotNull('usercode')
        ->where('usercode','!=',0)
        // ->whereNull('class','and')
        ->where('class','==',0)
        //  ->orWhere('class','==',$v)
        ->get();
    foreach ($stOld2 as $item){

        $characters = '0123456789abcdefghijklmnopqrstuvwxyz';
        $charactersLength = strlen($characters);
        do{
            $randomString = '';
            for ($i = 0; $i <= 8; $i++) {
                $randomString .= $characters[rand(0, $charactersLength - 1)];
            }
            $check =\App\User::where('private_code',$randomString)->get();


        }while(!$check->isEmpty());

        $user = \App\User::create([
            'private_code'=>$randomString,
            'level'=>'student',
            'usercode'=>$item->usercode,
            'userpass'=>$item->pass,
            'password'=>bcrypt($item->pass),
            'first_name'=>$item->getname,
            'last_name'=>$item->getfamily,
        ]);
        \App\InfoStudent::create(['user_id'=>$user->id]);
        \App\RegisterClassStudent::create([
            'user_id'=>$user->id,
            'base_id'=>$item->level,
            //'class_id'=>
        ]);
    }*/
    //$oCount = $oldClasses->count();
   // $users = \App\User::all();
//$row=4;
    //return view('welcome');
})->name('home.index');

route::get('check/acc/pp','CheckAccountController@copy')->name('check.account.copy');
route::get('check/acc','CheckAccountController@check')->name('check.account');
route::post('check/acc/st','CheckAccountController@checkAccount')->name('check.account.st');

// http error code pages
//route::get('404','Site/HttpCodePageController@404')->name('http.code.404');

Route::group(['namespace' => 'Auth'] , function (){
    // Authentication Routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::get('logout', 'LoginController@logout')->name('logout');

    // Registration Routes...
    Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'RegisterController@register');

    Route::get('confirm/code','RegisterController@confirmRegisterCodeForm')->name('register.confirm.code.form');
    Route::post('confirm/code','RegisterController@getCode')->name('register.confirm.code');

    Route::get('/insert/phone/{pc}','LoginController@insertPhoneForm')->name('user.insert.phone.form');
    Route::post('/check/phone/{pc}','LoginController@checkPhone')->name('user.check.phone');

   // Route::get('/check/phone/{pc}','LoginController@checkPhoneForm')->name('user.check.phone.exist');

    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset')->name('password.update');

    Route::get('password/confirm', 'ConfirmPasswordController@showConfirmForm')->name('password.confirm');
    Route::post('password/confirm', 'ConfirmPasswordController@confirm');

    Route::get('email/verify', 'VerificationController@show')->name('verification.notice');
    Route::get('email/verify/{id}/{hash}', 'VerificationController@verify')->name('verification.verify');
    Route::post('email/resend', 'VerificationController@resend')->name('verification.resend');



});



Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/Api/Azmoon/AzmoonClassController.php
<?php

namespace App\Http\Controllers\Admin\Api\Azmoon;

use App\Azmoon;
use App\AzmoonClass;
use App\EducationalClass;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AzmoonClassController extends Controller
{
    public function index($azmoonId)
    {
        $base_class = AzmoonClass::query()->where('azmoon_id', $azmoonId)->get();
        $class_list = [];
        if ($base_class->isNotEmpty()) {
            foreach ($base_class as $item) {
                $class = EducationalClass::query()->where('id', $item->educational_class_id)->first();
                $list = [
                    'id' => $item->id,
                    'class_id' => $class->id,
                    'class_title' => $class->class_title,
                    'base_title' => $class->educationBase->base_title,
                    'base_id' => $class->educationBase->id,
                ];

                array_push($class_list, $list);
            }
        }

        return response(['classes' => $class_list]);
    }

    /** @test */
    public function update(Request $request)
    {
        $azmoon=Azmoon::find($request['azmoon_id']);

        foreach ($request['class_list'] as $item) {
            $check = $azmoon->azmoonClasses->where('educational_class_id',$item['id'])->first();
            if (!$check) {
                //return "not";
                AzmoonClass::create([
                    'azmoon_id'=>$azmoon->id,
                    'educational_class_id'=>$item['id']
                ]);
            }
        }
        return response('success');
    }


    public function destroy($azmoonClassId)
    {
        $azmoonClass = AzmoonClass::find($azmoonClassId);
        $azmoonClass->delete();
        return response('success');
    }
}

app/Http/Controllers/Admin/Api/Azmoon/ExcelReportController.php
<?php

namespace App\Http\Controllers\Admin\Api\Azmoon;

use App\Azmoon;
use App\Exports\AzmoonReport;
use App\Http\Controllers\Controller;
use Carbon\Carbon;
use Illuminate\Support\Facades\Storage;
use Maatwebsite\Excel\Facades\Excel;

class ExcelReportController extends Controller
{
    public function exportReport($azmoonId)
    {
        $azmoon = Azmoon::find($azmoonId);
        $filename = Carbon::now()->format('Ymdhms') . '-azmoon.xlsx';
        Excel::store(new AzmoonReport($azmoon), $filename);
        $file = Storage::get($filename);
        if ($file) {
            $fileLink = 'data:application/vnd.ms-excel;base64,' . base64_encode($file);
            @chmod(Storage::disk('local')->path($filename), 0755);
            @unlink(Storage::disk('local')->path($filename));
        }
        return response()->json([
            'data' => $fileLink,
            'filename' => $filename,
            'message' => 'Products are successfully exported.'
        ], 200);
    }
}

app/Http/Controllers/Admin/Api/Azmoon/NormalPorseshnamehFileController.php
<?php

namespace App\Http\Controllers\Admin\Api\Azmoon;

use App\Azmoon;
use App\AzmoonPorseshnameh;
use App\AzmoonSoalatFile;
use App\Http\Controllers\Controller;
use App\Traits\UploaderFile;
use Illuminate\Http\Request;

class NormalPorseshnamehFileController extends Controller
{
    use UploaderFile;
    public function index($azmoonId)
    {
        $files=AzmoonSoalatFile::query()->where('azmoon_id',$azmoonId)->latest()->get();
        $data=[];
        if ($files->isNotEmpty()) {
            foreach ($files as $file) {
                $data[] = [
                    'id'=>$file->id,
                    'azmoon_id'=>$file->azmoon_id,
                    'title'=>$file->title == '' ? 'بی نام' : $file->title,
                    'pdf_file'=>asset($file->pdf_file),
                    'image'=>asset($file->image),
                ];
            }
        }
        return response()->json(['files'=>$data]);
    }

    public function imageUpload(Request $request)
    {
        $input = [
            'azmoon_id'=>$request->input('azmoon_id'),
            'title'=>$request->input('file_name'),
        ];
        $file = $request->file('file');
        if ($file) {
            $input['image'] = $this->uploadImage($file,'azmoon_soal');
        }

        AzmoonSoalatFile::create($input);
        return response('success');

    }

    public function soalPoreshnameh($id)
    {
        $azmoon = Azmoon::query()->where('id',$id)->first();
        $soal = $azmoon->soal;
        $soals = AzmoonPorseshnameh::query()->where('azmoon_id',$id)->first();
        return response(['soal'=>$soal,'soals'=>$soals]);
    }

    public function soalPoreshnamehStore(Request $request)
    {
        try {
            $keys = AzmoonPorseshnameh::query()->where('azmoon_id',$request->input('azmoon_id'))->first();
            if ($keys) {
                $keys->update([
                    'number_of_question'=>$request['number_of_question'],
                    'correct_key'=>$request['correct_key'],
                ]);
                $msg_type='success';
                $msg="کلید سوالات با موفقیت بروزرسانی شد!";
            }else{
                AzmoonPorseshnameh::create($request->all());
                $msg_type='info';
                $msg="کلید سوالات با موفقیت ثبت گردید!";
            }

            return response(['code'=>$msg_type,'message'=>$msg,'error_info'=>'']);
        } catch (\Throwable $th) {
            $msg_type='error';
            $msg="در ثبت اطلاعات مشکل بوجود آمد!!";
            return response(['code'=>$msg_type,'message'=>$msg,'error_info'=>$th->getMessage()]);
        }
    }

    public function destroy($id)
    {
        $file = AzmoonSoalatFile::query()->where('id',$id)->first();
        if ($file) {
            if (file_exists(asset($file->image)))
            unlink($file->image);

        if (file_exists(asset($file->pdf_file)))
            unlink($file->pdf_file);
        $file->delete();
        }
        return response('success');
    }
}

resources/views/panel/admin/azmoon/exclusives/all.blade.php
@extends('panel.admin.master')
@section('page_title') تفکیک آزمون@endsection
@section('content')

    <div class="page-content">
        <!-- Page-Title -->
        <div class="page-title-box">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <div class="col-md-4">
                        <h4 class="page-title mb-1">تفکیک پایه و کلاس  </h4>
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item active">تفکیک آزمون براساس پایه و کلاس آموزشی</li>
                        </ol>
                    </div>
                    <div class="col-md-8">
                        <div class="float-right d-md-block">
                            <a href="{{ route('admin.exclusives.create',['id'=>$azmoon]) }}"
                               class="btn btn-light btn-rounded dropdown-toggle"><i class="dripicons-plus mr-1"></i>
                                <b>افزودن تفکیک</b>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- end page title end breadcrumb -->
        <div class="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="header-title">لیست آزمون و پایه </h4>
                                <p class="card-title-desc">
                                    @include('alert_messages.alerts')
                                </p>
                                @if($exclusives->isNotEmpty())
                                    <div class="table-responsive">
                                        <table class="table mb-0">
                                            <thead>
                                            <tr>
                                                <th>آزمون </th>
                                                <th>پایه</th>
                                                <th>کلاس ها</th>
                                                <th>تنظیمات</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            @foreach($exclusives as $exc)
                                                <tr>
                                                    <td>{{ $exc->azmoon->azmoon_title }}</td>
                                                    <td>{{ $exc->base->base_title }}</td>
                                                    <td>{{ $exc->classes }}</td>
                                                    <td>
                                                        <div class="btn btn-group-lg">
                                                            <form action="{{ route('admin.exclusives.destroy',$exc->id) }}" method="post">
                                                                @method('delete')
                                                                @csrf
                                                                <div class="btn-group btn-group-xs">
                                                                    @can('role-edit')
                                                                    <button onclick="return confirm('از حذف دسته تفکیک مطمئن هستید؟')" type="submit" class="btn btn-danger" title="حذف ">
                                                                        <i class="ti-trash"></i>
                                                                        <b>حذف</b>
                                                                    </button>
                                                                    @endcan
                                                                </div>
                                                            </form>
                                                        </div>
                                                    </td>
                                                </tr>
                                            @endforeach

                                            </tbody>
                                        </table>
                                    </div>

                                @else
                                    <div class="">

                                        <div class="alert alert-info alert-dismissible fade show" role="alert">
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true">×</span>
                                            </button>
                                            <strong>توجه!</strong> لیست تفکیک خالی می باشد!
                                        </div>

                                    </div>
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/panel/admin/azmoon/exclusives/edit.blade.php
@extends('panel.admin.master')
@section('page_title')ویرایش تیکت@endsection

@section('content')

    <div class="page-content">
        <!-- Page-Title -->
        <div class="page-title-box">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <div class="col-md-8">
                        <h4 class="page-title mb-1">تیکت </h4>
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item active">فرم ویرایش تیکت </li>
                        </ol>
                    </div>

                </div>
            </div>
        </div>
        <!-- end page title end breadcrumb -->
        <div class="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="header-title"> فرم ویرایش تیکت</h4>
                                <p class="card-title-desc">
                                    @include('alert_messages.alerts')
                                </p>
                                <form action="{{ route('admin.ticketCategories.update',$ticketCategory) }}" method="post">
                                    @csrf
                                    @method('patch')
                                    <div class="row">
                                        <div class="col-md-4 mb-3">
                                            <label for="ticket_category_name">عنوان تیکت</label>
                                            <input type="text"
                                                   class="form-control"
                                                   name="ticket_category_name"
                                                   value="{{ old('ticket_category_name',$ticketCategory->ticket_category_name) }}"
                                                   id="ticket_category_name" placeholder="عنوان تیکت را وارد کنید">
                                            @error('error')
                                            <ul class="parsley-errors-list is-invalid"
                                                id="parsley-id-5" aria-hidden="false">
                                                <li class="parsley-required">عنوان تیکت را وارد کنید</li>
                                            </ul>
                                            @enderror
                                        </div>
                                        <div class="col-md-4 mb-3">
                                            <label for="ticket_category_latin"><span>عنوان دسته بندی تیکت </span> <span class="text-danger">به لاتین</span></label>
                                            <input type="text"
                                                   class="form-control"
                                                   name="ticket_category_latin"
                                                   value="{{ old('ticket_category_latin',$ticketCategory->ticket_category_latin) }}"
                                                   id="ticket_category_latin" placeholder="عنوان دسته بندی تیکت را وارد کنید">
                                            @error('error')
                                            <ul class="parsley-errors-list is-invalid"
                                                id="parsley-id-5" aria-hidden="false">
                                                <li class="parsley-required">ضریب را وارد کنید</li>
                                            </ul>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="form-group mt-4">
                                            <button type="submit"
                                                    class="btn btn-primary waves-effect waves-light">
                                                ثبت اطلاعات
                                            </button>
                                            <button type="reset"
                                                    class="btn btn-secondary waves-effect m-l-5">
                                                تازه سازی فرم
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection